org: differenthalibut
console: true
service: auction-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  environment:
    AUCTION_TABLE_NAME: ${self:custom.AuctionTable.name}
  iam:
    role:
      statements:
        - ${file(iam/AuctionTableIAM.yml):AuctionTableIAM}
        # - Effect: Allow
        #   Action: 
        #     - dynamodb:PutItem
        #   Resource: 
        #     - arn:aws:dynamodb:eu-west-1:218270470437:table/AuctionTable
        #     - arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/AuctionTable


resources:
  Resources:
    AuctionTable: ${file(resources/AuctionsTable.yml):AuctionTable}
    # AuctionTable:
    #   Type: AWS::DynamoDB::Table
    #   Properties:
    #     TableName: AuctionTable
    #     BillingMode: PAY_PER_REQUEST
    #     AttributeDefinitions:
    #       - AttributeName: id
    #         AttributeType: S
    #     KeySchema:
    #       - AttributeName: id
    #         KeyType: HASH
  
functions:
  createAuction:
    handler: src/handlers/createAuction.handler
    events:
      - http:
          method: POST
          path: /auction
custom:
  AuctionTable:
    name: !Ref AuctionTable
    arn: !GetAtt AuctionTable.Arn
  bundle:
    linting: false